<?php

use yii\helpers\Html;
use yii\grid\GridView;
use yii\widgets\Pjax;
/* @var $this yii\web\View */
/* @var $searchModel common\models\fireCache\FireCacheSearch */
/* @var $dataProvider yii\data\ActiveDataProvider */

$this->title = 'Fire Caches';
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="fire-cache-index">

    <h1><?= Html::encode($this->title) ?></h1>
    <?php Pjax::begin(); ?>
    <?php // echo $this->render('_search', ['model' => $searchModel]); ?>

    <p>
        <?= Html::a('Create Fire Cache', ['create'], ['class' => 'btn btn-success']) ?>
    </p>

    <?= GridView::widget([
        'dataProvider' => $dataProvider,
        'filterModel' => $searchModel,
        'columns' => [
            ['class' => 'yii\grid\SerialColumn'],

            // 'irwinID',
            // 'recordSource',
            // 'createdBySystem',
            // 'createdOnDateTime',
            // 'modifiedBySystem',
            //'modifiedOnDateTime',
            //'inConflict',
            //'conflictParentIrwinId',
            //'uniqueFireIdentifier',
            //'fireDiscoveryDateTime',
            //'pooProtectingUnit',
            //'localIncidentIdentifier',
            //'dispatchCenterId',
            'incidentName',
            //'fireCause',
            //'incidentTypeKind',
            //'incidentTypeCategory',
            //'initialLatitude',
            //'initialLongitude',
            'discoveryAcres',
            //'pooLatitude',
            //'pooLongitude',
            //'pooJurisdictionalUnit',
            //'pooState',
            //'pooCounty',
            //'pooFips',
            //'pooLandownerKind',
            //'pooLandownerCategory',
            //'initialResponseAcres',
            //'initialFireStrategy',
            //'firecodeRequested',
            //'abcdMisc',
            //'fireCode',
            //'fsJobCode',
            //'fsOverrideCode',
            //'isComplex',
            //'complexParentIrwinId',
            //'isFSAssisted',
            //'isMultiJurisdictional',
            //'isTrespass',
            //'isReimbursable',
            //'dailyAcres',
            //'calculatedAcres',
            //'totalIncidentPersonnel',
            //'fireMgmtComplexity',
            //'incidentCommanderName',
            //'incidentManagementOrganization',
            //'fatalities',
            //'injuries',
            //'residencesDestroyed',
            //'residencesThreatened',
            //'otherStructuresDestroyed',
            //'otherStructuresThreatened',
            //'estimatedCostToDate',
            //'estimatedContainmentDate',
            //'percentContained',
            //'percentPerimeterToBeContained',
            //'ics209ReportDateTime',
            //'ics209ReportStatus',
            //'containmentDateTime',
            //'controlDateTime',
            //'fireOutDateTime',
            //'finalAcres',
            //'gacc',
            //'isValid',
            //'adsPermissionState',
            //'unitIDValidation',
            //'incidentShortDescription',
            //'significantEvents:ntext',
            //'primaryFuelModel',
            //'weatherConcerns:ntext',
            //'projectedIncidentActivity12:ntext',
            //'plannedActions:ntext',
            //'ics209Remarks:ntext',
            //'ics209ReportForTimePeriodFrom',
            //'ics209ReportForTimePeriodTo',
            //'pooCity',
            //'pooIncidentJurisdictionalAgency',
            //'pooLegalDescQtrQtr',
            //'pooLegalDescQtr',
            //'pooLegalDescRange',
            //'pooLegalDescSection',
            //'pooLegalDescTownship',
            //'pooLegalDescPrincipalMeridian',
            'fireClassId',
            'fireClass',
            //'created_at',
            //'updated_at',
            //'fireIgnitionDateTime',
            //'fireCauseGeneral',
            //'fireCauseSpecific',
            //'fireCauseInvestigatedIndicator',
            //'pooJurisdictionalUnitParentUnit',
            //'initialResponseDateTime',
            //'initialFireStrategyMetIndicator',
            //'finalStrategyAttainedDateTime',
            //'fireGrowthCessationDateTime',
            //'predominantFuelModel',
            //'finalFireReportApprovedByUnit',
            //'finalFireReportApprovedBy',
            //'finalFireReportApprovedByTitle',
            //'finalFireReportApprovedDate',
            //'finalFireReportNarrative:ntext',
            //'unifiedCommand',
            //'wfdssDecisionStatus',
            //'fireBehaviorGeneral:ntext',
            //'fireBehaviorGeneral1:ntext',
            //'fireBehaviorGeneral2:ntext',
            //'fireBehaviorGeneral3:ntext',
            //'fireBehaviorDescription:ntext',
            //'secondaryFuelModel:ntext',
            //'additionalFuelModel:ntext',
            //'summaryFuelModel:ntext',
            //'fireStrategyMonitorPercent',
            //'fireStrategyConfinePercent',
            //'fireStrategyPointZonePercent',
            //'fireStrategyFullSuppPercent',
            //'projectedIncidentActivity24:ntext',
            //'projectedIncidentActivity48:ntext',
            //'projectedIncidentActivity72:ntext',
            //'projectedIncidentActivity72Plus:ntext',
            //'fiscallyResponsibleUnit',
            //'mergeParentIrwinId',
            //'criticalResourceNeeds',
            //'fireDepartmentID',
            //'hasFatalities',
            //'hasInjuries',
            //'inFuelTreatment',
            //'inNFPORS',
            //'isFireCauseInvestigated',
            //'isFireCodeRequested',
            //'isInitialFireStrategyMet',
            //'isQuarantined',
            //'isUnifiedCommand',
            //'pooDispatchCenterID',
            //'pooJurisdictionalAgency',
            //'pooPredictiveServiceAreaID',
            //'pooProtectingAgency',
            //'predominantFuelGroup',

            ['class' => 'yii\grid\ActionColumn'],
        ],
    ]); ?>
    <?php Pjax::end(); ?>
</div>
