<?php

use yii\helpers\Html;
use yii\widgets\DetailView;

/* @var $this yii\web\View */
/* @var $model common\models\fireCache\FireCache */

$this->title = $model->irwinID;
$this->params['breadcrumbs'][] = ['label' => 'Fire Caches', 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="fire-cache-view">

    <h1><?= Html::encode($this->title) ?></h1>

    <p>
        <?= Html::a('Update', ['update', 'id' => $model->irwinID], ['class' => 'btn btn-primary']) ?>
        <?= Html::a('Delete', ['delete', 'id' => $model->irwinID], [
            'class' => 'btn btn-danger',
            'data' => [
                'confirm' => 'Are you sure you want to delete this item?',
                'method' => 'post',
            ],
        ]) ?>
    </p>

    <?= DetailView::widget([
        'model' => $model,
        'attributes' => [
            'irwinID',
            'recordSource',
            'createdBySystem',
            'createdOnDateTime',
            'modifiedBySystem',
            'modifiedOnDateTime',
            'inConflict',
            'conflictParentIrwinId',
            'uniqueFireIdentifier',
            'fireDiscoveryDateTime',
            'pooProtectingUnit',
            'localIncidentIdentifier',
            'dispatchCenterId',
            'incidentName',
            'fireCause',
            'incidentTypeKind',
            'incidentTypeCategory',
            'initialLatitude',
            'initialLongitude',
            'discoveryAcres',
            'pooLatitude',
            'pooLongitude',
            'pooJurisdictionalUnit',
            'pooState',
            'pooCounty',
            'pooFips',
            'pooLandownerKind',
            'pooLandownerCategory',
            'initialResponseAcres',
            'initialFireStrategy',
            'firecodeRequested',
            'abcdMisc',
            'fireCode',
            'fsJobCode',
            'fsOverrideCode',
            'isComplex',
            'complexParentIrwinId',
            'isFSAssisted',
            'isMultiJurisdictional',
            'isTrespass',
            'isReimbursable',
            'dailyAcres',
            'calculatedAcres',
            'totalIncidentPersonnel',
            'fireMgmtComplexity',
            'incidentCommanderName',
            'incidentManagementOrganization',
            'fatalities',
            'injuries',
            'residencesDestroyed',
            'residencesThreatened',
            'otherStructuresDestroyed',
            'otherStructuresThreatened',
            'estimatedCostToDate',
            'estimatedContainmentDate',
            'percentContained',
            'percentPerimeterToBeContained',
            'ics209ReportDateTime',
            'ics209ReportStatus',
            'containmentDateTime',
            'controlDateTime',
            'fireOutDateTime',
            'finalAcres',
            'gacc',
            'isValid',
            'adsPermissionState',
            'unitIDValidation',
            'incidentShortDescription',
            'significantEvents:ntext',
            'primaryFuelModel',
            'weatherConcerns:ntext',
            'projectedIncidentActivity12:ntext',
            'plannedActions:ntext',
            'ics209Remarks:ntext',
            'ics209ReportForTimePeriodFrom',
            'ics209ReportForTimePeriodTo',
            'pooCity',
            'pooIncidentJurisdictionalAgency',
            'pooLegalDescQtrQtr',
            'pooLegalDescQtr',
            'pooLegalDescRange',
            'pooLegalDescSection',
            'pooLegalDescTownship',
            'pooLegalDescPrincipalMeridian',
            'fireClassId',
            'fireClass',
            'created_at',
            'updated_at',
            'fireIgnitionDateTime',
            'fireCauseGeneral',
            'fireCauseSpecific',
            'fireCauseInvestigatedIndicator',
            'pooJurisdictionalUnitParentUnit',
            'initialResponseDateTime',
            'initialFireStrategyMetIndicator',
            'finalStrategyAttainedDateTime',
            'fireGrowthCessationDateTime',
            'predominantFuelModel',
            'finalFireReportApprovedByUnit',
            'finalFireReportApprovedBy',
            'finalFireReportApprovedByTitle',
            'finalFireReportApprovedDate',
            'finalFireReportNarrative:ntext',
            'unifiedCommand',
            'wfdssDecisionStatus',
            'fireBehaviorGeneral:ntext',
            'fireBehaviorGeneral1:ntext',
            'fireBehaviorGeneral2:ntext',
            'fireBehaviorGeneral3:ntext',
            'fireBehaviorDescription:ntext',
            'secondaryFuelModel:ntext',
            'additionalFuelModel:ntext',
            'summaryFuelModel:ntext',
            'fireStrategyMonitorPercent',
            'fireStrategyConfinePercent',
            'fireStrategyPointZonePercent',
            'fireStrategyFullSuppPercent',
            'projectedIncidentActivity24:ntext',
            'projectedIncidentActivity48:ntext',
            'projectedIncidentActivity72:ntext',
            'projectedIncidentActivity72Plus:ntext',
            'fiscallyResponsibleUnit',
            'mergeParentIrwinId',
            'criticalResourceNeeds',
            'fireDepartmentID',
            'hasFatalities',
            'hasInjuries',
            'inFuelTreatment',
            'inNFPORS',
            'isFireCauseInvestigated',
            'isFireCodeRequested',
            'isInitialFireStrategyMet',
            'isQuarantined',
            'isUnifiedCommand',
            'pooDispatchCenterID',
            'pooJurisdictionalAgency',
            'pooPredictiveServiceAreaID',
            'pooProtectingAgency',
            'predominantFuelGroup',
        ],
    ]) ?>

</div>
